#!/usr/bin/env python3
"""Generate the README ASCII flame SVG.

The flame is procedural: each character is selected from a deterministic heat
field, not from a hand-written ASCII block.
"""

from __future__ import annotations

from dataclasses import dataclass
from html import escape
from math import exp, sin
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "public" / "profile-hero.svg"

WIDTH = 1600
HEIGHT = 500
COLS = 108
ROWS = 34
CHAR_W = 13.2
ROW_H = 17.2
CHARS = " .:-=+*#%@"


@dataclass(frozen=True)
class FlameLine:
    text: str
    x: float
    y: float
    heat: float


def lobe(x: float, y: float, cx: float, cy: float, sx: float, sy: float, amp: float) -> float:
    dx = (x - cx) / sx
    dy = (y - cy) / sy
    return amp * exp(-(dx * dx + dy * dy))


def flame_heat(x: float, y: float) -> float:
    """Return procedural heat for normalized x [-1, 1], y [0, 1], bottom up."""
    root_taper = 0.30 + 0.70 * min(1.0, y / 0.24)
    base_width = (0.82 * (1.0 - y) ** 0.58 + 0.045) * root_taper
    center = 0.13 * sin(y * 8.8) - 0.08 * y
    silhouette = max(0.0, 1.0 - abs(x - center) / base_width)
    silhouette = silhouette**1.9

    tongues = (
        lobe(x, y, -0.24, 0.34, 0.22, 0.32, 0.92)
        + lobe(x, y, 0.14, 0.46, 0.24, 0.42, 1.10)
        + lobe(x, y, -0.02, 0.72, 0.18, 0.28, 1.32)
        + lobe(x, y, 0.24, 0.82, 0.12, 0.20, 0.86)
        + lobe(x, y, -0.18, 0.88, 0.10, 0.16, 0.72)
    )

    hollow = lobe(x, y, 0.0, 0.28, 0.18, 0.20, 0.62)
    lick = 0.12 * sin((x * 10.0) + (y * 22.0)) + 0.08 * sin((x * 23.0) - (y * 15.0))
    taper = 0.24 + 0.90 * y
    bottom_fade = 0.20 + 0.80 * min(1.0, y / 0.18)
    heat = ((silhouette * taper + tongues - hollow + lick) / 2.45) * bottom_fade
    return max(0.0, min(1.0, heat))


def make_lines() -> list[FlameLine]:
    pending: list[tuple[str, float, float, float]] = []
    for row in range(ROWS):
        y_norm = 1.0 - row / (ROWS - 1)
        chars: list[str] = []
        row_heat = 0.0
        active = False
        for col in range(COLS):
            x_norm = (col / (COLS - 1)) * 2.0 - 1.0
            heat = flame_heat(x_norm, y_norm)
            row_heat = max(row_heat, heat)
            if heat < 0.135:
                chars.append(" ")
                continue
            active = True
            idx = min(len(CHARS) - 1, int(heat * (len(CHARS) - 1)))
            chars.append(CHARS[idx])

        if active:
            raw_text = "".join(chars).rstrip()
            leading_spaces = len(raw_text) - len(raw_text.lstrip())
            text = raw_text[leading_spaces:]
            raw_x = (row * 2.4) + leading_spaces * CHAR_W
            pending.append((text, raw_x, 70 + row * ROW_H, row_heat))
    min_x = min(raw_x for _, raw_x, _, _ in pending)
    lines = [
        FlameLine(text=text, x=285 + raw_x - min_x, y=y, heat=heat)
        for text, raw_x, y, heat in pending
    ]
    return lines


def color_for(heat: float) -> str:
    if heat > 0.82:
        return "#ffd66b"
    if heat > 0.66:
        return "#ff9d28"
    if heat > 0.46:
        return "#f06a18"
    return "#9d3510"


def text_nodes(lines: list[FlameLine], class_name: str, dx: float = 0, dy: float = 0) -> str:
    nodes: list[str] = []
    for line in lines:
        nodes.append(
            f'      <text class="{class_name}" x="{line.x + dx:.1f}" y="{line.y + dy:.1f}" '
            f'fill="{color_for(line.heat)}">{escape(line.text)}</text>'
        )
    return "\n".join(nodes)


def build_svg(lines: list[FlameLine]) -> str:
    ghost = text_nodes(lines, "ghost", dx=-24, dy=14)
    flame = text_nodes(lines, "flame")
    core_lines = [line for line in lines if line.heat > 0.62]
    core = text_nodes(core_lines, "core", dx=16, dy=-8)

    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-labelledby="title desc">
  <title id="title">LIghtJUNction procedural ASCII flame</title>
  <desc id="desc">A generated ASCII flame made from a deterministic heat field.</desc>
  <rect width="{WIDTH}" height="{HEIGHT}" fill="#050505"/>
  <!-- Generated by scripts/generate-readme-ascii-flame.py. Do not hand-edit the flame. -->
  <defs>
    <filter id="glow" x="-25%" y="-25%" width="150%" height="150%">
      <feGaussianBlur stdDeviation="2.4" result="blur"/>
      <feMerge>
        <feMergeNode in="blur"/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>
  </defs>
  <style>
    text {{ font-family: "IBM Plex Mono", "SFMono-Regular", Consolas, "Liberation Mono", monospace; letter-spacing: 0; }}
    .flame {{ font-size: 20px; font-weight: 900; white-space: pre; }}
    .ghost {{ font-size: 20px; font-weight: 900; opacity: .26; white-space: pre; }}
    .core {{ font-size: 20px; font-weight: 900; opacity: .72; white-space: pre; }}
    .mark {{ fill: #ffbf61; font-size: 18px; font-weight: 900; }}
    .dim {{ fill: #9b3a10; font-size: 14px; }}
  </style>
  <g transform="translate(-110 -20) rotate(-4) scale(1.02)" filter="url(#glow)" xml:space="preserve">
    <g>
      <animateTransform attributeName="transform" type="translate" values="-12 8;10 -8;-6 5;-12 8" dur="1.25s" repeatCount="indefinite"/>
{ghost}
    </g>
    <g>
      <animateTransform attributeName="transform" type="translate" values="0 0;18 -10;-8 7;0 0" dur="1.55s" repeatCount="indefinite"/>
{flame}
    </g>
    <g>
      <animate attributeName="opacity" values=".48;.92;.62;.84;.48" dur=".95s" repeatCount="indefinite"/>
{core}
    </g>
  </g>
  <text class="mark" x="44" y="54">LIghtJUNction</text>
  <text class="dim" x="44" y="80">procedural ASCII flame</text>
</svg>
"""


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build_svg(make_lines()), encoding="utf-8")
    print(f"generated {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
