#!/usr/bin/env python3
"""Generate the README ASCII flame SVG.

The flame is procedural: each character is selected from a deterministic heat
field, not from a hand-written ASCII block.
"""

from __future__ import annotations

from dataclasses import dataclass
from html import escape
from math import sin
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "public" / "profile-hero.svg"

WIDTH = 1600
HEIGHT = 500
COLS = 96
ROWS = 36
CHAR_W = 13.6
ROW_H = 14.0
CHARS = " .:-=+*#%@"


@dataclass(frozen=True)
class FlameLine:
    text: str
    x: float
    y: float
    heat: float


def tongue(
    x: float,
    y: float,
    base_x: float,
    tip_x: float,
    y0: float,
    y1: float,
    max_width: float,
    amp: float,
) -> float:
    if y < y0 or y > y1:
        return 0.0
    t = (y - y0) / (y1 - y0)
    center = base_x + (tip_x - base_x) * t + 0.045 * sin(t * 10.0)
    width = 0.018 + max_width * (sin(t * 3.14159) ** 0.72) * (1.0 - 0.18 * t)
    edge = max(0.0, 1.0 - abs(x - center) / width)
    vertical = (sin(t * 3.14159) ** 0.22) * (0.72 + 0.38 * t)
    return amp * (edge**1.35) * vertical


def flame_heat(x: float, y: float) -> float:
    """Return procedural heat for normalized x [-1, 1], y [0, 1], bottom up."""
    # Main center tongue
    y0, y1 = 0.05, 0.85
    base_heat = 0.0
    if y0 <= y <= y1:
        t = (y - y0) / (y1 - y0)
        center = 0.04 * sin(t * 6.28)
        w = 0.28 * (sin(t * 3.14159) ** 0.5) * (1.0 - 0.15 * t)
        if w > 0:
            dist = abs(x - center) / w
            if dist < 1.0:
                base_heat = (1.0 - dist) ** 1.4

    # Left tongue lick
    left_heat = 0.0
    ly0, ly1 = 0.10, 0.65
    if ly0 <= y <= ly1:
        lt = (y - ly0) / (ly1 - ly0)
        lcenter = -0.15 - 0.04 * lt + 0.02 * sin(lt * 6.28)
        lw = 0.14 * (sin(lt * 3.14159) ** 0.6)
        if lw > 0:
            ldist = abs(x - lcenter) / lw
            if ldist < 1.0:
                left_heat = 0.75 * (1.0 - ldist) ** 1.5

    # Right tongue lick
    right_heat = 0.0
    ry0, ry1 = 0.12, 0.70
    if ry0 <= y <= ry1:
        rt = (y - ry0) / (ry1 - ry0)
        rcenter = 0.15 + 0.04 * rt + 0.02 * sin(rt * 6.28)
        rw = 0.14 * (sin(rt * 3.14159) ** 0.6)
        if rw > 0:
            rdist = abs(x - rcenter) / rw
            if rdist < 1.0:
                right_heat = 0.75 * (1.0 - rdist) ** 1.5


    heat = max(base_heat, left_heat, right_heat)
    if heat <= 0.0:
        return 0.0

    # Add a gentle grain/noise at the edges
    grain = 0.04 * sin(x * 30.0 + y * 50.0) * heat
    heat = heat + grain
    return max(0.0, min(1.0, heat))




def make_lines() -> list[FlameLine]:
    pending: list[tuple[str, float, float, float]] = []
    for row in range(ROWS):
        y_norm = 1.0 - row / (ROWS - 1)
        chars: list[str] = []
        row_heat = 0.0
        active = False
        for col in range(COLS):
            x_norm = (col / (COLS - 1)) * 2.0 - 1.0
            heat = flame_heat(x_norm, y_norm)
            row_heat = max(row_heat, heat)
            if heat < 0.115:
                chars.append(" ")
                continue
            active = True
            idx = min(len(CHARS) - 1, int(heat * (len(CHARS) - 1)))
            chars.append(CHARS[idx])

        if active:
            raw_text = "".join(chars).rstrip()
            leading_spaces = len(raw_text) - len(raw_text.lstrip())
            text = raw_text[leading_spaces:]
            raw_x = leading_spaces * CHAR_W
            pending.append((text, raw_x, 70 + row * ROW_H, row_heat))
    min_x = min(raw_x for _, raw_x, _, _ in pending)
    lines = [
        FlameLine(text=text, x=530 + raw_x - min_x, y=y, heat=heat)
        for text, raw_x, y, heat in pending
    ]

    return lines


def color_for(heat: float) -> str:
    if heat > 0.82:
        return "#ffd66b"
    if heat > 0.66:
        return "#ff9d28"
    if heat > 0.46:
        return "#f06a18"
    return "#9d3510"


def text_nodes(lines: list[FlameLine], class_name: str, dx: float = 0, dy: float = 0) -> str:
    nodes: list[str] = []
    for line in lines:
        nodes.append(
            f'      <text class="{class_name}" x="{line.x + dx:.1f}" y="{line.y + dy:.1f}" '
            f'fill="{color_for(line.heat)}">{escape(line.text)}</text>'
        )
    return "\n".join(nodes)


def build_svg(lines: list[FlameLine]) -> str:
    ghost = text_nodes(lines, "ghost", dx=-24, dy=14)
    flame = text_nodes(lines, "flame")
    core_lines = [line for line in lines if line.heat > 0.62]
    core = text_nodes(core_lines, "core", dx=16, dy=-8)

    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-labelledby="title desc">
  <title id="title">LIghtJUNction procedural ASCII flame</title>
  <desc id="desc">A generated ASCII flame made from a deterministic heat field.</desc>
  <rect width="{WIDTH}" height="{HEIGHT}" fill="#050505"/>
  <!-- Generated by scripts/generate-readme-ascii-flame.py. Do not hand-edit the flame. -->
  <defs>
    <filter id="glow" x="-25%" y="-25%" width="150%" height="150%">
      <feGaussianBlur stdDeviation="2.4" result="blur"/>
      <feMerge>
        <feMergeNode in="blur"/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>
  </defs>
  <style>
    text {{ font-family: "IBM Plex Mono", "SFMono-Regular", Consolas, "Liberation Mono", monospace; letter-spacing: 0; }}
    .flame {{ font-size: 19px; font-weight: 900; white-space: pre; }}
    .ghost {{ font-size: 19px; font-weight: 900; opacity: .24; white-space: pre; }}
    .core {{ font-size: 19px; font-weight: 900; opacity: .70; white-space: pre; }}
    .mark {{ fill: #ffbf61; font-size: 18px; font-weight: 900; }}
    .dim {{ fill: #9b3a10; font-size: 14px; }}
  </style>
  <g transform="translate(40 -10) rotate(-1) scale(1.02)" filter="url(#glow)" xml:space="preserve">
    <g>
      <animateTransform attributeName="transform" type="translate" values="-12 8;10 -8;-6 5;-12 8" dur="1.25s" repeatCount="indefinite"/>
{ghost}
    </g>
    <g>
      <animateTransform attributeName="transform" type="translate" values="0 0;18 -10;-8 7;0 0" dur="1.55s" repeatCount="indefinite"/>
{flame}
    </g>
    <g>
      <animate attributeName="opacity" values=".48;.92;.62;.84;.48" dur=".95s" repeatCount="indefinite"/>
{core}
    </g>
  </g>
  <text class="mark" x="44" y="54">LIghtJUNction</text>
  <text class="dim" x="44" y="80">procedural ASCII flame</text>
</svg>
"""


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build_svg(make_lines()), encoding="utf-8")
    print(f"generated {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
