#!/usr/bin/env python3
"""Generate the canonical WORK_REPORT index with collapsible archives."""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


DEFAULT_REPORTS_DIR = Path(__file__).resolve().parents[1] / "WORK_REPORT"
REPORT_RE = re.compile(r"^(\d{4})/(\d{2})/(\d{2})\.md$")


@dataclass(frozen=True, order=True)
class Report:
    year: str
    month: str
    day: str
    path: Path

    @property
    def date(self) -> str:
        return f"{self.year}-{self.month}-{self.day}"

    @property
    def rel_link(self) -> str:
        return self.path.as_posix()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate WORK_REPORT/index.md from YYYY/MM/DD.md diary files."
    )
    parser.add_argument(
        "--reports-dir",
        type=Path,
        default=DEFAULT_REPORTS_DIR,
        help=f"WORK_REPORT directory to scan (default: {DEFAULT_REPORTS_DIR})",
    )
    parser.add_argument(
        "--index",
        type=Path,
        default=None,
        help="Index file to write (default: <reports-dir>/index.md)",
    )
    parser.add_argument(
        "--recent-count",
        type=int,
        default=14,
        help="Number of newest reports to keep expanded before folding archives.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated markdown instead of writing the index file.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the existing index is not up to date.",
    )
    return parser.parse_args()


def collect_reports(reports_dir: Path) -> list[Report]:
    reports: list[Report] = []

    for path in reports_dir.glob("[0-9][0-9][0-9][0-9]/[0-9][0-9]/[0-9][0-9].md"):
        rel = path.relative_to(reports_dir)
        match = REPORT_RE.match(rel.as_posix())
        if not match:
            continue
        year, month, day = match.groups()
        reports.append(Report(year=year, month=month, day=day, path=rel))

    return sorted(reports, key=lambda report: report.date, reverse=True)


def render_index(reports: list[Report], recent_count: int) -> str:
    if recent_count < 0:
        raise ValueError("--recent-count must be non-negative")

    recent = reports[:recent_count]
    archived = reports[recent_count:]
    lines = [
        "# Work Report Index",
        "",
        "<!-- Generated by scripts/sync-work-report-index.py. Do not edit by hand. -->",
        "",
        f"Total reports: {len(reports)}",
        "",
    ]

    if recent:
        lines.extend(["## Recent Reports", ""])
        lines.extend(f"- [{report.date}]({report.rel_link})" for report in recent)
        lines.append("")

    if archived:
        lines.extend(["## Archived Reports", ""])
        by_year: dict[str, list[Report]] = defaultdict(list)
        for report in archived:
            by_year[report.year].append(report)

        for year in sorted(by_year, reverse=True):
            year_reports = by_year[year]
            lines.extend([
                "<details>",
                f"<summary>{year} ({len(year_reports)} reports)</summary>",
                "",
            ])

            by_month: dict[str, list[Report]] = defaultdict(list)
            for report in year_reports:
                by_month[report.month].append(report)

            for month in sorted(by_month, reverse=True):
                month_reports = by_month[month]
                lines.extend([
                    "<details>",
                    f"<summary>{year}-{month} ({len(month_reports)} reports)</summary>",
                    "",
                ])
                lines.extend(
                    f"- [{report.date}]({report.rel_link})" for report in month_reports
                )
                lines.extend(["", "</details>", ""])

            lines.extend(["</details>", ""])

    if not reports:
        lines.extend(["No daily reports found.", ""])

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    args = parse_args()
    reports_dir = args.reports_dir.resolve()
    index_path = (args.index or reports_dir / "index.md").resolve()

    if not reports_dir.is_dir():
        print(f"reports directory does not exist: {reports_dir}", file=sys.stderr)
        return 2

    try:
        content = render_index(collect_reports(reports_dir), args.recent_count)
    except ValueError as error:
        print(str(error), file=sys.stderr)
        return 2

    if args.dry_run:
        print(content, end="")
        return 0

    if args.check:
        existing = index_path.read_text(encoding="utf-8") if index_path.exists() else ""
        if existing != content:
            print(f"index is not up to date: {index_path}", file=sys.stderr)
            return 1
        return 0

    index_path.write_text(content, encoding="utf-8")
    print(f"updated {index_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
